version: "3.9"

services:
  fitness-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness-backend
    ports:
      - "18080:18080"
    volumes:
      # Persist SQLite DB so it survives rebuilds
      - ./fitness.db:/app/fitness.db


    restart: unless-stopped
